# Generated by Django 3.2.3 on 2023-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0007_alter_voivodeship_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voivodeship',
            name='name',
            field=models.CharField(choices=[('VOIVODESHIP1', 'Voivodeship 1'), ('VOIVODESHIP2', 'Voivodeship 2'), ('VOIVODESHIP3', 'Voivodeship 3')], max_length=40),
        ),
    ]
